FROM brunneis/python:3.7.0-ubuntu-18.04

WORKDIR /labelme

# install apt
# RUN apt update && \
#     apt install -y --no-install-recommends pyqt5-dev-tools make python3-pip python3-pyqt5 python-pyqt5 gcc

# install pip
# RUN pip install -U pip && \
#     pip3 install labelme pycocotools

